import {
  ShoppingCart,
  Home,
  Car,
  Coffee,
  Utensils,
  Zap,
  Heart,
  Plane,
  Gift,
  Gamepad2,
  BookOpen,
  Music,
  Shirt,
  Dumbbell,
  Baby,
  Dog,
  Briefcase,
  DollarSign,
  TrendingUp,
  Building2,
  Landmark,
  PiggyBank,
  Smartphone,
  Wifi,
  Droplets,
  Flame,
  Bus,
  Train,
  Bike,
  Fuel,
  Stethoscope,
  Pill,
  GraduationCap,
  Wrench,
  Scissors,
  Camera,
  Monitor,
  CreditCard,
  Wallet,
  MoreHorizontal,
  type LucideIcon,
} from 'lucide-react-native';

export const iconMap: Record<string, LucideIcon> = {
  'shopping-cart': ShoppingCart,
  home: Home,
  car: Car,
  coffee: Coffee,
  utensils: Utensils,
  zap: Zap,
  heart: Heart,
  plane: Plane,
  gift: Gift,
  gamepad2: Gamepad2,
  'book-open': BookOpen,
  music: Music,
  shirt: Shirt,
  dumbbell: Dumbbell,
  baby: Baby,
  dog: Dog,
  briefcase: Briefcase,
  'dollar-sign': DollarSign,
  'trending-up': TrendingUp,
  building2: Building2,
  landmark: Landmark,
  'piggy-bank': PiggyBank,
  smartphone: Smartphone,
  wifi: Wifi,
  droplets: Droplets,
  flame: Flame,
  bus: Bus,
  train: Train,
  bike: Bike,
  fuel: Fuel,
  stethoscope: Stethoscope,
  pill: Pill,
  'graduation-cap': GraduationCap,
  wrench: Wrench,
  scissors: Scissors,
  camera: Camera,
  monitor: Monitor,
  'credit-card': CreditCard,
  wallet: Wallet,
  'more-horizontal': MoreHorizontal,
};

export function getIcon(name: string): LucideIcon {
  return iconMap[name] ?? MoreHorizontal;
}
